/*
 * IONOS DBaaS REST API
 * An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-14T13:10:25.683Z[Etc/UTC]")
public class Configuration {
    public static final String IONOS_USERNAME_ENV_VAR = "IONOS_USERNAME";
    public static final String IONOS_PASSWORD_ENV_VAR = "IONOS_PASSWORD";
    public static final String IONOS_TOKEN_ENV_VAR    = "IONOS_TOKEN";
    public static final String IONOS_API_URL_ENV_VAR  = "IONOS_API_URL";

    public static final String DEFAULT_IONOS_SERVER_URL = "https://api.ionos.com/databases/postgresql";
    public static final String DEFAULT_IONOS_BASE_PATH  = "/databases/postgresql";

    private static ApiClient defaultApiClient = new ApiClient();

    /**
     * Get the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }

    /**
     * Set the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @param apiClient API client
     */
    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient = apiClient;
    }
}
